[theme]
base = "light"
primaryColor = "#cca865"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f5f0e8"
textColor = "#1a1917"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200
enableStaticServing = true